### ISSUE TITLE
CurseForge mark on Low Fire compitable with 1.19.2

### ISSUE THREAD

**Issue by Disguys** [UltimateBoomer/mc-lowfire#4]
Hello, please put a note on CurseForge that it is compatible with 1.19.2, I need it for the Modpack.

**Comment by UltimateBoomer** [comment]
I've added 1.19.2 to the compatible versions.

**Comment by Disguys** [comment]
thanks, it would be very good if you marked version 1.18.2 on CurseForge, because there is still 1.18
