### ISSUE TITLE
1.19..3 compatability

### ISSUE THREAD

**Issue by RU-B0** [UltimateBoomer/mc-lowfire#6]
I understand that this is probably the most annoying type of issue ever, but (even after modifying the jar to accept any game version, which is what I do when new versions aren't out), checking if a newly compiled build from source code would work, and removing other mods, the game still crashes when a world is loaded with this mod. For now I'll use vanilla tweaks's low fire, but I prefer this mod because its something that should just be a setting. It's a great mod, and I hope that you have a good day!

**Comment by Disguys** [comment]
Now available on GitHub - https://github.com/UltimateBoomer/mc-lowfire/releases/tag/3.0.1

**Comment by Disguys** [comment]
But I'm still waiting for the version on the CurseForge website, since I need this mod for my modpack 😀

**Comment by Disguys** [comment]
Now also available on CurseForge
